language: generic
dist: bionic

# Install vx using DESTDIR and prefix
install:
  - make DESTDIR=/tmp/vx prefix=/usr install
  - test -x /tmp/vx/usr/bin/vx
  - /tmp/vx/usr/bin/vx . true

script:
  - make test V=2
